GET http://localhost:3001/api/notes/1
###
GET http://localhost:3001/api/notes/2
###
GET http://localhost:3001/api/notes/3
###
GET http://localhost:3001/api/notes/64975883c8d1aadf28c67c0b
###
GET http://localhost:3001/api/notes/64973a47f161fc63f2721662
###
